In [1]:
import numpy as np
x=np.array([5,10,15,20])
print("one dimensional array: ",x)

one dimensional array:  [ 5 10 15 20]


In [2]:
import numpy as np
y=np.array([[10,20,30,40],[8,16,24,32]])
print("two dimensional array: ",y)


two dimensional array:  [[10 20 30 40]
 [ 8 16 24 32]]


In [3]:

import numpy as np
z=np.zeros((4,4))
print("\n array with all zeros:\n",z)


 array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
import numpy as np
a=np.random.random((3,3))
print("\n random array:\n",a)


 random array:
 [[0.16285948 0.20131655 0.29514714]
 [0.19198747 0.23346525 0.32277814]
 [0.96045686 0.58906381 0.21970093]]


In [5]:
import numpy as np
b=np.arange(0,20,3)
print("\n range value \n",b)



 range value 
 [ 0  3  6  9 12 15 18]


In [6]:
import numpy as np
arr=np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24]])
new=arr.reshape((3,4))
print("\n original array: \n",arr)
print("\n reshaped array: \n",new)



 original array: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]

 reshaped array: 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [8]:
import numpy as np
arr=np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24],[26,28,30]])
z=np.zeros((5,3))
r=np.random.random((5,3))
b=np.arange(0,20,3)
new=arr.reshape((3,5))
print("\n created 5x3 array: \n",arr)
print("\n all zeros array: \n",z)
print("\n random numbers array: \n",r)
print("\n range with step value \n",b)
print("\n reshaped 3x5 array: \n",new)


 created 5x3 array: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]
 [26 28 30]]

 all zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 random numbers array: 
 [[0.00933364 0.94372656 0.29464804]
 [0.94359441 0.4013908  0.74522612]
 [0.36206171 0.77247484 0.29676347]
 [0.53074288 0.13034113 0.57898183]
 [0.22053279 0.35625928 0.72976687]]

 range with step value 
 [ 0  3  6  9 12 15 18]

 reshaped 3x5 array: 
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [11]:
import numpy as np
arr=np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24],[26,28,30]])
print("number of dimension:",arr.ndim)
print("shape of the array:",arr.shape)
fl=arr.flatten()
print("Flattened array:",fl)

number of dimension: 2
shape of the array: (5, 3)
Flattened array: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [2]:
import numpy as np
arr=np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24],[26,28,30]])
print("\n Array element type:",arr.dtype)


 Array element type: int32


In [4]:

import numpy as np
arr=np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24],[26,28,30]])
size=len(arr)
print("arr.size",size)
                                                                                                                                                

arr.size 5


In [6]:
import numpy as np
x= np.array([[1,2,3],[4,5,6]])
new=x.astype('f')
print("\nconverted array element\n",new)
print("\n converted array:\n",new.dtype)


converted array element
 [[1. 2. 3.]
 [4. 5. 6.]]

 converted array:
 float32
