In [11]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)

(array([1, 4], dtype=int64),)


In [17]:
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

6


In [18]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))

[2 4 5 6 7 9]


In [19]:
import numpy as np
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))

[[4 7 9]
 [1 4 9]]


In [24]:
arr=np.array([31,78,69,88])
x=arr<70
newarr=arr[x]
print(newarr)

[31 69]
