In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
sl1=arr[2:6]
print(sl1)

[3 4 5 6]


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
sl1=arr[::2]
print(sl1)

[1 3 5 7 9]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
rev=arr[::-1]
print("Reversed array:",rev)

Reversed array: [9 8 7 6 5 4 3 2 1]


In [16]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=arr[0:2,1:3]
print(subarr)

[[2 3]
 [5 6]]


In [25]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=arr[0:3,0:1]
sbarr=arr[1:2,0:3]
print("1st column:")
print(subarr)
print("2nd row:")
print(sbarr)


1st column:
[[1]
 [4]
 [7]]
2nd row:
[[4 5 6]]


In [26]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])


1
6


In [31]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1])

20


In [32]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[-1])

50


In [33]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[-3])

30


In [34]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [35]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [36]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
res=np.hstack((arr1,arr2))
print(res)

[[1 2 5 6]
 [3 4 7 8]]


In [37]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
res=np.vstack((arr1,arr2))
print(res)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
res=np.dstack((arr1,arr2))
print(res)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [44]:
import numpy as np 
arr=np.array([1,2,3,4,5,6])
res=np.array_split(arr,3)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [45]:
import numpy as np 
arr=np.array([1,2,3,4,5,6])
res=np.array_split(arr,4)
print(res)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
import numpy as np
