In [4]:
#Create an 1-D array. Determine which data type, shape, size, length, reversed array, slice the array, print the data which is greater thean 7.
import numpy as np
a=np.array([1,2,3,11,16,24,40])
print("\nOne dimensional array:",a)
print("\nType:",a.dtype)
print("\nShape of array:",a.shape)
print("\nArray size:", a.size)
print("\nArray length:",len(a))
rev=a[::-1]
print("\nReversed array:",rev)
slice1=a[2:6]
print("\nSliced array:",slice1)
print("\nElements greater than 7:",a[a>7])


One dimensional array: [ 1  2  3 11 16 24 40]

Type: int32

Shape of array: (7,)

Array size: 7

Array length: 7

Reversed array: [40 24 16 11  3  2  1]

Sliced array: [ 3 11 16 24]

Elements greater than 7: [11 16 24 40]


In [11]:
#Create a 2-D array. Reshape the array, sort the array,slice the array,extracrt the rows and columns of array.
import numpy as np
b=np.array([[3,1,7],[4,2,9],[10,6,2],[11,2,5]])
print("Two dimensional array:",b)
newarr=b.reshape((3,4))
print("\n Reshaped array [4,3]:\n", newarr)
print("Sorted array:",np.sort(b))
slice1=b[2:4]
print("\nSliced array:",slice1)
col=b[:,0]
print("1st Column:",col)
row=b[0,:]
print("1st row:",row)

Two dimensional array: [[ 3  1  7]
 [ 4  2  9]
 [10  6  2]
 [11  2  5]]

 Reshaped array [4,3]:
 [[ 3  1  7  4]
 [ 2  9 10  6]
 [ 2 11  2  5]]
Sorted array: [[ 1  3  7]
 [ 2  4  9]
 [ 2  6 10]
 [ 2  5 11]]

Sliced array: [[10  6  2]
 [11  2  5]]
1st Column: [ 3  4 10 11]
1st row: [3 1 7]
